### ISSUE TITLE
Target multiple framework 

### ISSUE THREAD

**Issue by amerkoleci** [discosultan/VulkanCore#15]
The new sdk format support target frameworks, consider adding net40, net45 and even xamarin70 maybe,  without reference net standard only.

Take look here: 
https://github.com/onovotny/MSBuildSdkExtras

Real example here:
https://github.com/lunet-io/markdig/blob/master/src/Markdig/Markdig.csproj

**Comment by discosultan** [comment]
@amerkoleci Thanks for pointing this out! It's something I haven't really thought about. Is there any particular use case it would solve for you?

**Comment by amerkoleci** [comment]
Not my case but immagine that I don't like to reference .NET standard from .NET framework application and I don't want to target .NET 4.6.1 which is minimal target for .NET standard one.

**Comment by discosultan** [comment]
These are currently the dependencies that prevent targeting below `net461;netstandard1.3`:

- `Marshal.GetDelegateForFunctionPointer<TDelegate>(IntPtr)`
- `Buffer.MemoryCopy(void*, void*, long long)`
- `RuntimeInformation.IsOSPlatform(OSPlatform)`
- `Encoding.GetString(byte*, int)`

**Comment by amerkoleci** [comment]
Those are all replaceable calls, I can submit PR tho

**Comment by WardBenjamin** [comment]
In my opinion, this isn't worth it. Any new projects will be targeting a new version of .NET Framework, .NET Core, or .NET Standard, and Vulkan is only supported on relatively new systems/GPUs anyway.

**Comment by WardBenjamin** [comment]
Truth be told, the project upgrade from net45 to a .NET Standard-compliant version of .NET Framework is also trivial, assuming you're using modern tooling.

**Comment by discosultan** [comment]
What I'm more interested in is if consumers of VulkanCore would benefit if it was also targeting `netstandard2.0`. From what I've heard, if a `netcoreapp2.0`+ targets a `netstandard2.0` version of a library instead of `netstandard1.3`, it should provide some perks when it comes to dependency resolution. I don't have a clear overview of what exactly, though.

**Comment by WardBenjamin** [comment]
@discosultan assuming there's no features that we need from `netstandard2.0`, Microsoft recommends "to target the lowest version of .NET Standard possible," according to [dotnet/standard#versions.md](https://github.com/dotnet/standard/blob/master/docs/versions.md), mainly because it's then supported by the most platforms.

As a side note, `netstandard1.3` will _always_ be compatible with `netstandard2.0` and any other higher version since .NET Standard versions are exclusively additive.

**Comment by TrabacchinLuigi** [comment]
I would add net5 too, it's true that .net5 can use the net standard packages, but from the perspective of .net5 net standard is something from the past, not really useful anymore since all the new framework is cross platform

**Comment by amerkoleci** [comment]
Hi @TrabacchinLuigi,
I'm maintaining netstandard 2.0 and net5 vulkan bindings (https://github.com/amerkoleci/Vortice.Vulkan)

**Comment by TrabacchinLuigi** [comment]
why two codebases ? what's wrong with adding target frameworks to this one ?

**Comment by amerkoleci** [comment]
Nothing wrong, I know the author is not working on this one.

**Comment by TrabacchinLuigi** [comment]
so vortice also use new api ? sincerely vortice repo seems less complete than this one ... inspired less trust in me ... want some help ? i could try to port the samples so i get to try vulkan AND do something useful ...
