### ISSUE TITLE
Any hope for a Vulkan 1.1+ update

### ISSUE THREAD

**Issue by dpeter99** [discosultan/VulkanCore#17]
I'm using this lib in a project and it would be nice if this was updated to a the newer Vulkan versions

I would like to help but i don't know too much about language bindings

**Comment by discosultan** [comment]
Hi @dpeter99 and sorry for late reply.

Version 1.1 moved a lot of things around (a lot of extensions were stabilized and moved to the core API, for example). That's one of those cases which requires non-trivial amount of work due to the fact that VulkanCore is not fully generated from the spec.

Unfortunately, I don't have plans/time to tackle this in short future. Contributions are definitely welcome and don't even need to tackle the entire v1.1 upgrade. Simply moving a single API over would be a start.

I have been thinking about a slightly bigger overhaul of the project by taking advantage of the features coming in .NET Core 2.1 update. For example, employing `Span<T>` in public APIs to allow users to pass array-like structures by stack instead of heap. I might look into this and v1.1 upgrade together.

**Comment by amerkoleci** [comment]
Maybe you can start with addition, then some PR can be submitted as well.

**Comment by discosultan** [comment]
I have created a `v1.1` branch [here](https://github.com/discosultan/VulkanCore/tree/v1.1). It's still very early in dev but already contains additions like `vkEnumerateInstanceVersion` and `VkDebugUtilsMessengerEXT`.

**Comment by BastianBlokland** [comment]
If you can use any help with the update i could help as well.

**Comment by discosultan** [comment]
I have a list of all the commands that need to be either added or promoted from an extension to core. I'll add them all here sometime today as a list of checkboxes for a better overview of overall progress.

**Comment by dpeter99** [comment]
I would suggest you make a tracking issue for the needed things

**Comment by discosultan** [comment]
Closing in favor of https://github.com/discosultan/VulkanCore/issues/27
